#! /bin/bash

cp ~/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.8.5/appengine-api-1.0-sdk-1.8.5.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/googlecode/objectify/objectify/4.0b3/objectify-4.0b3.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/google/appengine/appengine-api-labs/1.7.6/appengine-api-labs-1.7.6.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/google/appengine/tools/appengine-mapreduce/0.2/appengine-mapreduce-0.2.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/google/appengine/tools/appengine-gcs-client/0.3.2/appengine-gcs-client-0.3.2.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/google/appengine/tools/appengine-pipeline/0.1/appengine-pipeline-0.1.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/googlecode/charts4j/charts4j/1.3/charts4j-1.3.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/json/json/20090211/json-20090211.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/easymock/easymock/3.0/easymock-3.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/cglib/cglib-nodep/2.2/cglib-nodep-2.2.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/objenesis/objenesis/1.2/objenesis-1.2.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/renjin-appengine/0.7.0-RC7-SNAPSHOT/renjin-appengine-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/renjin-script-engine/0.7.0-RC7-SNAPSHOT/renjin-script-engine-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/renjin-core/0.7.0-RC7-SNAPSHOT/renjin-core-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/gcc-runtime/0.7.0-RC7-SNAPSHOT/gcc-runtime-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/netlib/netlib-java/0.9.3-renjin-patched-2/netlib-java-0.9.3-renjin-patched-2.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/netlib/lapack/0.8/lapack-0.8.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/netlib/f2jutil/0.8/f2jutil-0.8.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/netlib/xerbla/0.8/xerbla-0.8.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/netlib/blas/0.8/blas-0.8.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/apache/commons/commons-vfs2/2.0/commons-vfs2-2.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/apache/maven/scm/maven-scm-api/1.4/maven-scm-api-1.4.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.4/maven-scm-provider-svnexe-1.4.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.4/maven-scm-provider-svn-commons-1.4.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/regexp/regexp/1.3/regexp-1.3.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/joda-time/joda-time/2.0/joda-time-2.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/edu/emory/mathcs/jtransforms/2.4/jtransforms-2.4.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/net/sf/jung/jung-api/2.0.1/jung-api-2.0.1.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/net/sourceforge/collections/collections-generic/4.01/collections-generic-4.01.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/net/sf/jung/jung-graph-impl/2.0.1/jung-graph-impl-2.0.1.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/asm/asm/4.0/asm-4.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/asm/asm-util/4.0/asm-util-4.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/asm/asm-tree/4.0/asm-tree-4.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/asm/asm-commons/4.0/asm-commons-4.0.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/com/sun/codemodel/codemodel/2.6/codemodel-2.6.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/stats/0.7.0-RC7-SNAPSHOT/stats-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/renjin-appl/0.7.0-RC7-SNAPSHOT/renjin-appl-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/renjin-gnur-runtime/0.7.0-RC7-SNAPSHOT/renjin-gnur-runtime-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/methods/0.7.0-RC7-SNAPSHOT/methods-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/datasets/0.7.0-RC7-SNAPSHOT/datasets-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/utils/0.7.0-RC7-SNAPSHOT/utils-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/grDevices/0.7.0-RC7-SNAPSHOT/grDevices-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/cran/truncreg/0.1-1-SNAPSHOT/truncreg-0.1-1-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/org/renjin/graphics/0.7.0-RC7-SNAPSHOT/graphics-0.7.0-RC7-SNAPSHOT.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib
cp ~/.m2/repository/mysql/mysql-connector-java/5.1.26/mysql-connector-java-5.1.26.jar ~/Documents/EclipseProjects/storedata/war/WEB-INF/lib