copy /Y %USERPROFILE%\.m2\repository\com\google\appengine\appengine-api-1.0-sdk\1.9.5\appengine-api-1.0-sdk-1.9.5.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\googlecode\objectify\objectify\4.1.3\objectify-4.1.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\javax\servlet\servlet-api\2.5\servlet-api-2.5.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\mysql\mysql-connector-java\5.1.26\mysql-connector-java-5.1.26.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\gson\gson-gwt\1.0\gson-gwt-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\gwt\gwt-servlet\2.7.0\gwt-servlet-2.7.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\gson\1.0\gson-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\service\1.0\service-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\gson.json.service_appengine\1.0\gson.json.service_appengine-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\gson.json.service\1.0\gson.json.service-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\service_appengine\1.0\service_appengine-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\utility\1.0\utility-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\spchopr\persistentmap\1.0\persistentmap-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\googlecode\gchart\gchart\2.7\gchart-2.7.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\junit\junit\4.11\junit-4.11.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\googlecode\gwt-crypto\gwt-crypto\2.3.0\gwt-crypto-2.3.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\commonjava\googlecode\markdown4j\markdown4j-gwt\1.0\markdown4j-gwt-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\commonjava\googlecode\emoji\emoji-gwt\1.0\emoji-gwt-1.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\joda-time\joda-time\2.3\joda-time-2.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\appengine\tools\appengine-pipeline\0.3-SNAPSHOT\appengine-pipeline-0.3-SNAPSHOT.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\json\json\20090211\json-20090211.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\guava\guava\18.0\guava-18.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\appengine\tools\appengine-gcs-client\0.4.4\appengine-gcs-client-0.4.4.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\apis\google-api-services-storage\v1-rev15-1.19.0\google-api-services-storage-v1-rev15-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\api-client\google-api-client-appengine\1.19.1\google-api-client-appengine-1.19.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\oauth-client\google-oauth-client-appengine\1.19.0\google-oauth-client-appengine-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\oauth-client\google-oauth-client-servlet\1.19.0\google-oauth-client-servlet-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\http-client\google-http-client-jdo\1.19.0\google-http-client-jdo-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\api-client\google-api-client-servlet\1.19.1\google-api-client-servlet-1.19.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\javax\jdo\jdo2-api\2.3-eb\jdo2-api-2.3-eb.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\javax\transaction\transaction-api\1.1\transaction-api-1.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\http-client\google-http-client\1.19.0\google-http-client-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\http-client\google-http-client-appengine\1.19.0\google-http-client-appengine-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\http-client\google-http-client-jackson2\1.19.0\google-http-client-jackson2-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.1.3\jackson-core-2.1.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\apache\commons\commons-math3\3.4\commons-math3-3.4.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\apis\google-api-services-bigquery\v2-rev188-1.19.1\google-api-services-bigquery-v2-rev188-1.19.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\api-client\google-api-client\1.19.1\google-api-client-1.19.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\oauth-client\google-oauth-client\1.19.0\google-oauth-client-1.19.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\com\google\guava\guava-jdk5\13.0\guava-jdk5-13.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\net\sourceforge\htmlunit\htmlunit\2.15\htmlunit-2.15.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\xalan\xalan\2.7.1\xalan-2.7.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\xalan\serializer\2.7.1\serializer-2.7.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpmime\4.3.3\httpmime-4.3.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\net\sourceforge\htmlunit\htmlunit-core-js\2.15\htmlunit-core-js-2.15.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\xerces\xercesImpl\2.11.0\xercesImpl-2.11.0.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\net\sourceforge\nekohtml\nekohtml\1.9.21\nekohtml-1.9.21.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\net\sourceforge\cssparser\cssparser\0.9.14\cssparser-0.9.14.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\w3c\css\sac\1.3\sac-1.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\eclipse\jetty\jetty-websocket\8.1.15.v20140411\jetty-websocket-8.1.15.v20140411.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\eclipse\jetty\jetty-util\8.1.15.v20140411\jetty-util-8.1.15.v20140411.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\eclipse\jetty\jetty-io\8.1.15.v20140411\jetty-io-8.1.15.v20140411.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\.m2\repository\org\eclipse\jetty\jetty-http\8.1.15.v20140411\jetty-http-8.1.15.v20140411.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\gwt-2.7.0\gwt-servlet.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\jsp-api.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\jsp\repackaged-appengine-jasper-el-6.0.29.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\jsp\repackaged-appengine-ant-1.7.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\jsp\repackaged-appengine-ant-launcher-1.7.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\jsp\repackaged-appengine-tomcat-juli-6.0.29.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\jsp\repackaged-appengine-jasper-6.0.29.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\appengine-local-runtime-shared.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\servlet-api.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\shared\el-api.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\appengine-tools-api.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\opt\user\appengine-api-labs\v1\appengine-api-labs.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\opt\user\appengine-endpoints\v1\appengine-endpoints-deps.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\opt\user\appengine-endpoints\v1\appengine-endpoints.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\opt\user\jsr107\v1\appengine-jsr107cache-1.9.5.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\opt\user\jsr107\v1\jsr107cache-1.1.jar %1\storedata\war\WEB-INF\lib\.
copy /Y %USERPROFILE%\temp\sdk\appengine-java-sdk-1.9.5\lib\user\appengine-api-1.0-sdk-1.9.5.jar %1\storedata\war\WEB-INF\lib\.