#! /bin/bash
cp ~/git/storedata/sdk/gwt-2.6.0/gwt-servlet.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.5/appengine-api-1.0-sdk-1.9.5.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/googlecode/objectify/objectify/4.1.3/objectify-4.1.3.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/appengine/tools/appengine-gcs-client/0.3.10/appengine-gcs-client-0.3.10.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/api-client/google-api-client/1.18.0-rc/google-api-client-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/oauth-client/google-oauth-client/1.18.0-rc/google-oauth-client-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client-jackson2/1.18.0-rc/google-http-client-jackson2-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client/1.18.0-rc/google-http-client-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.1.3/jackson-core-2.1.3.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/api-client/google-api-client-appengine/1.18.0-rc/google-api-client-appengine-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/oauth-client/google-oauth-client-appengine/1.18.0-rc/google-oauth-client-appengine-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/oauth-client/google-oauth-client-servlet/1.18.0-rc/google-oauth-client-servlet-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client-jdo/1.18.0-rc/google-http-client-jdo-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/api-client/google-api-client-servlet/1.18.0-rc/google-api-client-servlet-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/javax/jdo/jdo2-api/2.3-eb/jdo2-api-2.3-eb.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/javax/transaction/transaction-api/1.1/transaction-api-1.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client-appengine/1.18.0-rc/google-http-client-appengine-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/apis/google-api-services-storage/v1-rev1-1.18.0-rc/google-api-services-storage-v1-rev1-1.18.0-rc.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/renjin-appengine/0.7.0-RC7-SNAPSHOT/renjin-appengine-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/renjin-script-engine/0.7.0-RC7-SNAPSHOT/renjin-script-engine-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/renjin-core/0.7.0-RC7-SNAPSHOT/renjin-core-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/gcc-runtime/0.7.0-RC7-SNAPSHOT/gcc-runtime-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/netlib/netlib-java/0.9.3-renjin-patched-2/netlib-java-0.9.3-renjin-patched-2.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/netlib/lapack/0.8/lapack-0.8.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/netlib/f2jutil/0.8/f2jutil-0.8.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/netlib/xerbla/0.8/xerbla-0.8.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/netlib/blas/0.8/blas-0.8.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/commons/commons-vfs2/2.0/commons-vfs2-2.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/maven/scm/maven-scm-api/1.4/maven-scm-api-1.4.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.4/maven-scm-provider-svnexe-1.4.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.4/maven-scm-provider-svn-commons-1.4.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/regexp/regexp/1.3/regexp-1.3.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/edu/emory/mathcs/jtransforms/2.4/jtransforms-2.4.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/net/sf/jung/jung-api/2.0.1/jung-api-2.0.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/net/sourceforge/collections/collections-generic/4.01/collections-generic-4.01.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/net/sf/jung/jung-graph-impl/2.0.1/jung-graph-impl-2.0.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/asm/asm/4.0/asm-4.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/asm/asm-util/4.0/asm-util-4.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/asm/asm-tree/4.0/asm-tree-4.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/asm/asm-commons/4.0/asm-commons-4.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/sun/codemodel/codemodel/2.6/codemodel-2.6.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/stats/0.7.0-RC7-SNAPSHOT/stats-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/renjin-appl/0.7.0-RC7-SNAPSHOT/renjin-appl-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/renjin-gnur-runtime/0.7.0-RC7-SNAPSHOT/renjin-gnur-runtime-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/utils/0.7.0-RC7-SNAPSHOT/utils-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/grDevices/0.7.0-RC7-SNAPSHOT/grDevices-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/cran/truncreg/0.1-1-SNAPSHOT/truncreg-0.1-1-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/graphics/0.7.0-RC7-SNAPSHOT/graphics-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/methods/0.7.0-RC7-SNAPSHOT/methods-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/datasets/0.7.0-RC7-SNAPSHOT/datasets-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/cran/maxLik/1.1-2-SNAPSHOT/maxLik-1.1-2-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/cran/miscTools/0.6-16-SNAPSHOT/miscTools-0.6-16-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/cran/sandwich/2.2-10-SNAPSHOT/sandwich-2.2-10-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/cran/zoo/1.7-9-SNAPSHOT/zoo-1.7-9-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/cran/lattice/0.20-15-SNAPSHOT/lattice-0.20-15-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/renjin/grid/0.7.0-RC7-SNAPSHOT/grid-0.7.0-RC7-SNAPSHOT.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/mysql/mysql-connector-java/5.1.26/mysql-connector-java-5.1.26.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/gson/gson-gwt/1.0/gson-gwt-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/gwt/gwt-servlet/2.5.1/gwt-servlet-2.5.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/gson/1.0/gson-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/service/1.0/service-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/gson.json.service_appengine/1.0/gson.json.service_appengine-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/gson.json.service/1.0/gson.json.service-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/service_appengine/1.0/service_appengine-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/utility/1.0/utility-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/persistentmap/1.0/persistentmap-1.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/googlecode/gchart/gchart/2.7/gchart-2.7.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/junit/junit/4.11/junit-4.11.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/googlecode/gwt-crypto/gwt-crypto/2.3.0/gwt-crypto-2.3.0.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp-api.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-jasper-el-6.0.29.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-ant-1.7.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-ant-launcher-1.7.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-tomcat-juli-6.0.29.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-jasper-6.0.29.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/appengine-local-runtime-shared.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/servlet-api.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/el-api.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/appengine-tools-api.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/appengine-api-labs/v1/appengine-api-labs.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/appengine-endpoints/v1/appengine-endpoints-deps.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/appengine-endpoints/v1/appengine-endpoints.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/jsr107/v1/appengine-jsr107cache-1.9.5.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/jsr107/v1/jsr107cache-1.1.jar ~/git/storedata/war/WEB-INF/lib/.
cp ~/git/storedata/sdk/appengine-java-sdk-1.9.5/lib/user/appengine-api-1.0-sdk-1.9.5.jar ~/git/storedata/war/WEB-INF/lib/.
