#! /bin/bash
cp $1/storedata/sdk/gwt-2.6.0/gwt-servlet.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.5/appengine-api-1.0-sdk-1.9.5.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/googlecode/objectify/objectify/4.1.3/objectify-4.1.3.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/appengine/tools/appengine-gcs-client/0.3.10/appengine-gcs-client-0.3.10.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/api-client/google-api-client/1.18.0-rc/google-api-client-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/oauth-client/google-oauth-client/1.18.0-rc/google-oauth-client-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client-jackson2/1.18.0-rc/google-http-client-jackson2-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client/1.18.0-rc/google-http-client-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.1.3/jackson-core-2.1.3.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/api-client/google-api-client-appengine/1.18.0-rc/google-api-client-appengine-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/oauth-client/google-oauth-client-appengine/1.18.0-rc/google-oauth-client-appengine-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/oauth-client/google-oauth-client-servlet/1.18.0-rc/google-oauth-client-servlet-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client-jdo/1.18.0-rc/google-http-client-jdo-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/api-client/google-api-client-servlet/1.18.0-rc/google-api-client-servlet-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/javax/jdo/jdo2-api/2.3-eb/jdo2-api-2.3-eb.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/javax/transaction/transaction-api/1.1/transaction-api-1.1.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/http-client/google-http-client-appengine/1.18.0-rc/google-http-client-appengine-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/apis/google-api-services-storage/v1-rev1-1.18.0-rc/google-api-services-storage-v1-rev1-1.18.0-rc.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/mysql/mysql-connector-java/5.1.26/mysql-connector-java-5.1.26.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/gson/gson-gwt/1.0/gson-gwt-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/google/gwt/gwt-servlet/2.5.1/gwt-servlet-2.5.1.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/gson/1.0/gson-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/service/1.0/service-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/gson.json.service_appengine/1.0/gson.json.service_appengine-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/gson.json.service/1.0/gson.json.service-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/service_appengine/1.0/service_appengine-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/utility/1.0/utility-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/spchopr/persistentmap/1.0/persistentmap-1.0.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/googlecode/gchart/gchart/2.7/gchart-2.7.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/junit/junit/4.11/junit-4.11.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar $1/storedata/war/WEB-INF/lib/.
cp ~/.m2/repository/com/googlecode/gwt-crypto/gwt-crypto/2.3.0/gwt-crypto-2.3.0.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp-api.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-jasper-el-6.0.29.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-ant-1.7.1.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-ant-launcher-1.7.1.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-tomcat-juli-6.0.29.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/jsp/repackaged-appengine-jasper-6.0.29.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/appengine-local-runtime-shared.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/servlet-api.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/shared/el-api.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/appengine-tools-api.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/appengine-api-labs/v1/appengine-api-labs.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/appengine-endpoints/v1/appengine-endpoints-deps.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/appengine-endpoints/v1/appengine-endpoints.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/jsr107/v1/appengine-jsr107cache-1.9.5.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/opt/user/jsr107/v1/jsr107cache-1.1.jar $1/storedata/war/WEB-INF/lib/.
cp $1/storedata/sdk/appengine-java-sdk-1.9.5/lib/user/appengine-api-1.0-sdk-1.9.5.jar $1/storedata/war/WEB-INF/lib/.
